server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/CarlFlo06/TRABAJO_FINAL_FLORES_HUAUYA_CARLOS
          search-paths: config-data
  application:
    name: config-server
